---
- name: Create guacamole folder
  ansible.builtin.file:
    path: /etc/guacamole
    state: directory
    mode: '0755'

- name: Download guacamole client
  ansible.builtin.get_url:
    url: https://downloads.apache.org/guacamole/{{ guacamole_version }}/binary/guacamole-{{ guacamole_version }}.war
    dest: /etc/guacamole/guacamole.war

- name: Create a link to Tomcat webapps
  ansible.builtin.file:
    src: /etc/guacamole/guacamole.war
    dest: /var/lib/tomcat9/webapps/guacamole.war
    state: link

- name: Restart Tomcat service
  ansible.builtin.systemd_service:
    name: tomcat9
    state: restarted

- name: Restart guacd service
  ansible.builtin.systemd_service:
    name: guacd
    state: restarted
